/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserRouteImport } from './routes/_user'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as UserIndexRouteImport } from './routes/_user.index'
import { Route as UserTutorialsRouteImport } from './routes/_user.tutorials'
import { Route as UserTextbooksRouteImport } from './routes/_user.textbooks'
import { Route as UserTestsRouteImport } from './routes/_user.tests'
import { Route as UserSubscriptionRouteImport } from './routes/_user.subscription'
import { Route as UserSettingsRouteImport } from './routes/_user.settings'
import { Route as UserLeaderboardRouteImport } from './routes/_user.leaderboard'
import { Route as UserActivitiesRouteImport } from './routes/_user.activities'
import { Route as AuthWelcomeRouteImport } from './routes/_auth.welcome'
import { Route as AuthVerifyEmailRouteImport } from './routes/_auth.verify-email'
import { Route as AuthSummaryRouteImport } from './routes/_auth.summary'
import { Route as AuthSignInRouteImport } from './routes/_auth.sign-in'
import { Route as AuthSelectExamRouteImport } from './routes/_auth.select-exam'
import { Route as AuthRegisterRouteImport } from './routes/_auth.register'
import { Route as UserTestsExamsRouteImport } from './routes/_user.tests.exams'

const UserRoute = UserRouteImport.update({
  id: '/_user',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const UserIndexRoute = UserIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UserRoute,
} as any)
const UserTutorialsRoute = UserTutorialsRouteImport.update({
  id: '/tutorials',
  path: '/tutorials',
  getParentRoute: () => UserRoute,
} as any)
const UserTextbooksRoute = UserTextbooksRouteImport.update({
  id: '/textbooks',
  path: '/textbooks',
  getParentRoute: () => UserRoute,
} as any)
const UserTestsRoute = UserTestsRouteImport.update({
  id: '/tests',
  path: '/tests',
  getParentRoute: () => UserRoute,
} as any)
const UserSubscriptionRoute = UserSubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => UserRoute,
} as any)
const UserSettingsRoute = UserSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => UserRoute,
} as any)
const UserLeaderboardRoute = UserLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => UserRoute,
} as any)
const UserActivitiesRoute = UserActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => UserRoute,
} as any)
const AuthWelcomeRoute = AuthWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => AuthRoute,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSummaryRoute = AuthSummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSelectExamRoute = AuthSelectExamRouteImport.update({
  id: '/select-exam',
  path: '/select-exam',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const UserTestsExamsRoute = UserTestsExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => UserTestsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/register': typeof AuthRegisterRoute
  '/select-exam': typeof AuthSelectExamRoute
  '/sign-in': typeof AuthSignInRoute
  '/summary': typeof AuthSummaryRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/welcome': typeof AuthWelcomeRoute
  '/activities': typeof UserActivitiesRoute
  '/leaderboard': typeof UserLeaderboardRoute
  '/settings': typeof UserSettingsRoute
  '/subscription': typeof UserSubscriptionRoute
  '/tests': typeof UserTestsRouteWithChildren
  '/textbooks': typeof UserTextbooksRoute
  '/tutorials': typeof UserTutorialsRoute
  '/': typeof UserIndexRoute
  '/tests/exams': typeof UserTestsExamsRoute
}
export interface FileRoutesByTo {
  '/register': typeof AuthRegisterRoute
  '/select-exam': typeof AuthSelectExamRoute
  '/sign-in': typeof AuthSignInRoute
  '/summary': typeof AuthSummaryRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/welcome': typeof AuthWelcomeRoute
  '/activities': typeof UserActivitiesRoute
  '/leaderboard': typeof UserLeaderboardRoute
  '/settings': typeof UserSettingsRoute
  '/subscription': typeof UserSubscriptionRoute
  '/tests': typeof UserTestsRouteWithChildren
  '/textbooks': typeof UserTextbooksRoute
  '/tutorials': typeof UserTutorialsRoute
  '/': typeof UserIndexRoute
  '/tests/exams': typeof UserTestsExamsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_user': typeof UserRouteWithChildren
  '/_auth/register': typeof AuthRegisterRoute
  '/_auth/select-exam': typeof AuthSelectExamRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/summary': typeof AuthSummaryRoute
  '/_auth/verify-email': typeof AuthVerifyEmailRoute
  '/_auth/welcome': typeof AuthWelcomeRoute
  '/_user/activities': typeof UserActivitiesRoute
  '/_user/leaderboard': typeof UserLeaderboardRoute
  '/_user/settings': typeof UserSettingsRoute
  '/_user/subscription': typeof UserSubscriptionRoute
  '/_user/tests': typeof UserTestsRouteWithChildren
  '/_user/textbooks': typeof UserTextbooksRoute
  '/_user/tutorials': typeof UserTutorialsRoute
  '/_user/': typeof UserIndexRoute
  '/_user/tests/exams': typeof UserTestsExamsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/register'
    | '/select-exam'
    | '/sign-in'
    | '/summary'
    | '/verify-email'
    | '/welcome'
    | '/activities'
    | '/leaderboard'
    | '/settings'
    | '/subscription'
    | '/tests'
    | '/textbooks'
    | '/tutorials'
    | '/'
    | '/tests/exams'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/register'
    | '/select-exam'
    | '/sign-in'
    | '/summary'
    | '/verify-email'
    | '/welcome'
    | '/activities'
    | '/leaderboard'
    | '/settings'
    | '/subscription'
    | '/tests'
    | '/textbooks'
    | '/tutorials'
    | '/'
    | '/tests/exams'
  id:
    | '__root__'
    | '/_auth'
    | '/_user'
    | '/_auth/register'
    | '/_auth/select-exam'
    | '/_auth/sign-in'
    | '/_auth/summary'
    | '/_auth/verify-email'
    | '/_auth/welcome'
    | '/_user/activities'
    | '/_user/leaderboard'
    | '/_user/settings'
    | '/_user/subscription'
    | '/_user/tests'
    | '/_user/textbooks'
    | '/_user/tutorials'
    | '/_user/'
    | '/_user/tests/exams'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  UserRoute: typeof UserRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_user': {
      id: '/_user'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof UserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_user/': {
      id: '/_user/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof UserIndexRouteImport
      parentRoute: typeof UserRoute
    }
    '/_user/tutorials': {
      id: '/_user/tutorials'
      path: '/tutorials'
      fullPath: '/tutorials'
      preLoaderRoute: typeof UserTutorialsRouteImport
      parentRoute: typeof UserRoute
    }
    '/_user/textbooks': {
      id: '/_user/textbooks'
      path: '/textbooks'
      fullPath: '/textbooks'
      preLoaderRoute: typeof UserTextbooksRouteImport
      parentRoute: typeof UserRoute
    }
    '/_user/tests': {
      id: '/_user/tests'
      path: '/tests'
      fullPath: '/tests'
      preLoaderRoute: typeof UserTestsRouteImport
      parentRoute: typeof UserRoute
    }
    '/_user/subscription': {
      id: '/_user/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof UserSubscriptionRouteImport
      parentRoute: typeof UserRoute
    }
    '/_user/settings': {
      id: '/_user/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof UserSettingsRouteImport
      parentRoute: typeof UserRoute
    }
    '/_user/leaderboard': {
      id: '/_user/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof UserLeaderboardRouteImport
      parentRoute: typeof UserRoute
    }
    '/_user/activities': {
      id: '/_user/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof UserActivitiesRouteImport
      parentRoute: typeof UserRoute
    }
    '/_auth/welcome': {
      id: '/_auth/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof AuthWelcomeRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/verify-email': {
      id: '/_auth/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/summary': {
      id: '/_auth/summary'
      path: '/summary'
      fullPath: '/summary'
      preLoaderRoute: typeof AuthSummaryRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/select-exam': {
      id: '/_auth/select-exam'
      path: '/select-exam'
      fullPath: '/select-exam'
      preLoaderRoute: typeof AuthSelectExamRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_user/tests/exams': {
      id: '/_user/tests/exams'
      path: '/exams'
      fullPath: '/tests/exams'
      preLoaderRoute: typeof UserTestsExamsRouteImport
      parentRoute: typeof UserTestsRoute
    }
  }
}

interface AuthRouteChildren {
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthSelectExamRoute: typeof AuthSelectExamRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSummaryRoute: typeof AuthSummaryRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
  AuthWelcomeRoute: typeof AuthWelcomeRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthRegisterRoute: AuthRegisterRoute,
  AuthSelectExamRoute: AuthSelectExamRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSummaryRoute: AuthSummaryRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
  AuthWelcomeRoute: AuthWelcomeRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface UserTestsRouteChildren {
  UserTestsExamsRoute: typeof UserTestsExamsRoute
}

const UserTestsRouteChildren: UserTestsRouteChildren = {
  UserTestsExamsRoute: UserTestsExamsRoute,
}

const UserTestsRouteWithChildren = UserTestsRoute._addFileChildren(
  UserTestsRouteChildren,
)

interface UserRouteChildren {
  UserActivitiesRoute: typeof UserActivitiesRoute
  UserLeaderboardRoute: typeof UserLeaderboardRoute
  UserSettingsRoute: typeof UserSettingsRoute
  UserSubscriptionRoute: typeof UserSubscriptionRoute
  UserTestsRoute: typeof UserTestsRouteWithChildren
  UserTextbooksRoute: typeof UserTextbooksRoute
  UserTutorialsRoute: typeof UserTutorialsRoute
  UserIndexRoute: typeof UserIndexRoute
}

const UserRouteChildren: UserRouteChildren = {
  UserActivitiesRoute: UserActivitiesRoute,
  UserLeaderboardRoute: UserLeaderboardRoute,
  UserSettingsRoute: UserSettingsRoute,
  UserSubscriptionRoute: UserSubscriptionRoute,
  UserTestsRoute: UserTestsRouteWithChildren,
  UserTextbooksRoute: UserTextbooksRoute,
  UserTutorialsRoute: UserTutorialsRoute,
  UserIndexRoute: UserIndexRoute,
}

const UserRouteWithChildren = UserRoute._addFileChildren(UserRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  UserRoute: UserRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
